Repository doctrine/DoctrineModule, pull requests merged in 2021-12, with the labels that each got.

#756 Allow symfony console 6
  composer.json
Labels: Enhancement

#755 Add missing provide in composer.json
  composer.json
Labels: Bug

#760 Removed integration with laminas-console and laminas-mvc-console
  composer.json
  phpstan.neon
  psalm.xml
  src/Component/Console/Input/RequestInput.php
  src/Component/Console/Output/PropertyOutput.php
  src/ConfigProvider.php
  src/Controller/CliController.php
  src/GetConsoleUsage.php
  src/Module.php
  src/Mvc/Router/Console/SymfonyCli.php
  src/Service/CliControllerFactory.php
  src/Service/SymfonyCliRouteFactory.php
  tests/Component/Console/Input/RequestInputTest.php
  tests/Component/Console/Output/PropertyOutputTest.php
  tests/ConfigProviderTest.php
  tests/Controller/CliControllerTest.php
  tests/Controller/Mock/FailingCommand.php
  tests/ModuleTest.php
  tests/Mvc/Router/Console/SymfonyCliTest.php
  tests/TestConfiguration.php
Labels: BC Break, Feature Removal

#762 Require laminas-cache 3.x, drop support for laminas-cache 2.x
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  README.md
  composer.json
  docs/en/index.rst
  src/Cache/ZendStorageCache.php
Labels: BC Break

#763 Removed signatures related to laminas-servicemanager 2.x
  src/Service/Authentication/AdapterFactory.php
  src/Service/Authentication/AuthenticationServiceFactory.php
  src/Service/Authentication/StorageFactory.php
  src/Service/CacheFactory.php
  src/Service/CliFactory.php
  src/Service/DriverFactory.php
  src/Service/EventManagerFactory.php
  src/ServiceFactory/AbstractDoctrineServiceFactory.php
  src/Validator/Service/AbstractValidatorFactory.php
  tests/Service/Authentication/AdapterFactoryTest.php
  tests/Service/Authentication/AuthenticationServiceFactoryTest.php
  tests/Service/Authentication/StorageFactoryTest.php
  tests/Service/CacheFactoryTest.php
  tests/Service/DriverFactoryTest.php
  tests/Service/EventManagerFactoryTest.php
  tests/Validator/Service/NoObjectExistsFactoryTest.php
Labels: BC Break

#764 Drop support for PHP 7.3 and update dependencies
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  composer.json
  psalm.xml
  src/Paginator/Adapter/Collection.php
  src/Paginator/Adapter/Selectable.php
Labels: Enhancement

#765 Introduce typed properties where possible
  phpcs.xml.dist
  phpunit.xml.dist
  src/Authentication/Adapter/ObjectRepository.php
  src/Authentication/Storage/ObjectRepository.php
  src/Cache/DoctrineCacheStorage.php
  src/Cache/LaminasStorageCache.php
  src/Form/Element/GetProxy.php
  src/Form/Element/Proxy.php
  src/Options/Authentication.php
  src/Options/Cache.php
  src/Options/Driver.php
  src/Options/EventManager.php
  src/Paginator/Adapter/Collection.php
  src/Paginator/Adapter/Selectable.php
  src/Persistence/ProvidesObjectManager.php
  src/Service/AbstractFactory.php
  src/Service/CliFactory.php
  src/Validator/NoObjectExists.php
  src/Validator/ObjectExists.php
  src/Validator/Service/AbstractValidatorFactory.php
  src/Validator/Service/NoObjectExistsFactory.php
  src/Validator/Service/ObjectExistsFactory.php
  src/Validator/Service/UniqueObjectFactory.php
  src/Validator/UniqueObject.php
  tests/Authentication/Adapter/TestAsset/IdentityObject.php
  tests/Authentication/Adapter/TestAsset/PublicPropertiesIdentityObject.php
  tests/Cache/DoctrineCacheStorageTest.php
  tests/Form/Element/ObjectMultiCheckboxTest.php
  tests/Form/Element/ObjectRadioTest.php
  tests/Form/Element/ObjectSelectTest.php
  tests/Form/Element/ProxyAwareElementTestCase.php
  tests/Form/Element/ProxyTest.php
  tests/Form/Element/TestAsset/FormObject.php
  tests/Paginator/Adapter/CollectionAdapterTest.php
  tests/ServiceFactory/ModuleDefinedServicesTest.php
  tests/Validator/Service/NoObjectExistsFactoryTest.php
  tests/Validator/Service/ObjectExistsFactoryTest.php
  tests/Validator/Service/UniqueObjectFactoryTest.php
Labels: BC Break

#766 Mark `Module`, `ConfigProvider`, option classes and factories as final
  phpcs.xml.dist
  src/Authentication/Adapter/ObjectRepository.php
  src/Authentication/Storage/ObjectRepository.php
  src/Cache/DoctrineCacheStorage.php
  src/Cache/LaminasStorageCache.php
  src/ConfigProvider.php
  src/Form/Element/Exception/InvalidRepositoryResultException.php
  src/Module.php
  src/Options/Authentication.php
  src/Options/Cache.php
  src/Options/Driver.php
  src/Options/EventManager.php
  src/Paginator/Adapter/Selectable.php
  src/Persistence/ObjectManagerAwareInterface.php
  src/Service/AbstractFactory.php
  src/Service/Authentication/AdapterFactory.php
  src/Service/Authentication/AuthenticationServiceFactory.php
  src/Service/Authentication/StorageFactory.php
  src/Service/CacheFactory.php
  src/Service/CliFactory.php
  src/Service/DriverFactory.php
  src/Service/EventManagerFactory.php
  src/ServiceFactory/AbstractDoctrineServiceFactory.php
  src/Validator/NoObjectExists.php
  src/Validator/ObjectExists.php
  src/Validator/Service/AbstractValidatorFactory.php
  src/Validator/Service/Exception/ServiceCreationException.php
  src/Validator/Service/NoObjectExistsFactory.php
  src/Validator/Service/ObjectExistsFactory.php
  src/Validator/Service/UniqueObjectFactory.php
  src/Validator/UniqueObject.php
  tests/Authentication/Adapter/ObjectRepositoryTest.php
  tests/Authentication/Adapter/TestAsset/IdentityObject.php
  tests/Authentication/Adapter/TestAsset/PublicPropertiesIdentityObject.php
  tests/Authentication/Storage/ObjectRepositoryTest.php
  tests/Cache/DoctrineCacheStorageTest.php
  tests/Cache/LaminasStorageCacheTest.php
  tests/ConfigProviderTest.php
  tests/Form/Element/ObjectMultiCheckboxTest.php
  tests/Form/Element/ObjectSelectTest.php
  tests/Form/Element/ProxyTest.php
  tests/Form/Element/TestAsset/FormObject.php
  tests/Paginator/Adapter/CollectionAdapterTest.php
  tests/Paginator/Adapter/SelectableAdapterTest.php
  tests/ServiceFactory/ModuleDefinedServicesTest.php
  tests/Validator/NoObjectExistsTest.php
  tests/Validator/ObjectExistsTest.php
  tests/Validator/UniqueObjectTest.php
Labels: BC Break

#767 Updated upstream workflows
  .github/workflows/coding-standards.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: Enhancement

#768 Ensure broken laminas-stdlib 3.6.3 is not used
  composer.json
Labels: Enhancement

#769 Improved types and make static analysis more strict
  .github/workflows/release-on-milestone-closed.yml
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
  src/Cache/DoctrineCacheStorage.php
  src/Form/Element/ObjectMultiCheckbox.php
  src/Form/Element/ObjectRadio.php
  src/Form/Element/ObjectSelect.php
  src/Form/Element/Proxy.php
  src/Options/Authentication.php
  src/Options/Cache.php
  src/Paginator/Adapter/Collection.php
  src/Paginator/Adapter/Selectable.php
  src/Service/DriverFactory.php
  src/Validator/Service/AbstractValidatorFactory.php
  src/Validator/UniqueObject.php
  tests/Validator/Service/NoObjectExistsFactoryTest.php
  tests/Validator/Service/ObjectExistsFactoryTest.php
  tests/Validator/Service/UniqueObjectFactoryTest.php
  tests/Validator/TestAsset/DummyClass.php
Labels: Enhancement, BC Break

#770 Change return type to int for Countable implementations
  src/ConfigProvider.php
  src/Options/Cache.php
  src/Paginator/Adapter/Collection.php
  src/Paginator/Adapter/Selectable.php
Labels: BC Break
