Repository doctrine/DoctrineModule, pull requests merged in 2021-11, with the labels that each got.

#748 Fixed broken require_once in Module.php
  Module.php
Labels: Bug

#747 Updated composer scripts and removed coverage-checker
  .github/workflows/continuous-integration.yml
  build/.gitignore
  build/coverage-checker.php
  composer.json
Labels: Enhancement

#749 Updated links in docs
  README.md
  docs/en/index.rst
Labels: Documentation

#750 Simplified build matrix for continuous integration
  .github/workflows/continuous-integration.yml
Labels: Enhancement

#751 Add missing dependencies to composer.json to prevent unwanted soft dependencies
  composer.json
Labels: Bug

#752 Update upstream workflows and update PhpStan to 1.0
  .gitattributes
  .github/workflows/coding-standards.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  .gitignore
  composer.json
  phpstan.neon
  psalm.xml
  src/Form/Element/Proxy.php
  tests/Form/Element/ProxyAwareElementTestCase.php
  tests/ModuleTest.php
Labels: Enhancement

#753 Support for Laminas Cache v3
  .github/workflows/continuous-integration.yml
  composer.json
  tests/Service/CacheFactoryTest.php
Labels: Enhancement
